blog/urls.py
from django.urls import path
from . import views
from .views import PostCreateView, PostUpdateView, PostDeleteView , CatListView ,ViewPDF,DownloadPDF

urlpatterns = [
    path('', views.home, name='home'),
    path('new_post/', PostCreateView.as_view(), name='new_post'),
    path('allposts/', views.allposts, name='allposts'),
    path('about/', views.about, name='about'),
    # path('formm/', views.formm, name='formm'),

    path('pdf_view/', views.ViewPDF.as_view(), name="pdf_view"),
    path('pdf_download/', views.DownloadPDF.as_view(), name="pdf_download"),

    path('formmV/', views.FormmView.as_view(), name='formmV'),
    path('multilistformmV/', views.multilistformmV, name='multilistformmV'),
    path('multilistformmV_save/', views.multilistformmV_save, name='multilistformmV_save'),
    path('multilistformmBr/', views.multilistformmBr, name='multilistformmBr'),
    path('multilistformmBr_save/', views.multilistformmBr_save, name='multilistformmBr_save'),
    path('myform/', views.myform , name='myform'),

    path('uploadfile/', views.uploadfile, name='uploadfile'),

    path('adminapp/', views.admin_list, name='adminapp'),
    path('adminapp/<int:app_id>/', views.applist, name='adminapp'),
    path('applistmultistipform/<int:app_id>/', views.applistmultistipform, name='applistmultistipform'),
    path('applistmultistipformBr/<int:app_id>/', views.applistmultistipformBr, name='applistmultistipformBr'),

    # path('application/', views.adduser, name='application'),
    path('detail/<int:post_id>/', views.post_detail, name='detail'),
    path('category/<category>', CatListView.as_view(), name='category'),

    path('detail/<slug:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('detail/<slug:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('user.urls')),
    path('', include('notification.urls',namespace='notification')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.urls import reverse
from PIL import Image
from django.core.exceptions import ValidationError 

class Category(models.Model):

    name = models.CharField(max_length=100)


    def __str__(self):
        return self.name
    

class Post(models.Model):
    title = models.CharField(max_length=100)
    category=models.ForeignKey(Category , on_delete=models.PROTECT , default=1)
    image = models.ImageField(default='default.jpg', upload_to='posts_pics')
    content = models.TextField()
    post_date = models.DateTimeField(default=timezone.now)
    post_update = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        # return '/detail/{}'.format(self.pk)
        return reverse('detail', args=[self.pk])
        
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.width > 300 or img.height > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)    

    class Meta:
        ordering = ('-post_date', )


class Comment(models.Model):
    name = models.CharField(max_length=50, verbose_name='الاسم')
    email = models.EmailField(verbose_name='البريد الإلكتروني')
    body = models.TextField(verbose_name='التعليق')
    comment_date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return 'علق {} على {}.'.format(self.name, self.post)

    class Meta:
        ordering = ('-comment_date',)




def validate_employees_Number(value): 
    if value > 0:

        return value 
    else: 
        raise ValidationError("please enter valid number")        

class AppRegs(models.Model):
    
    
    companyName = models.CharField(max_length=50,blank=True, null=True)
    creationDate = models.DateField(blank=True, null=True)
    status = models.CharField(max_length=50,blank=True, null=True)
    associatesNumber = models.CharField(max_length=50,blank=True, null=True)
    employeesNumber = models.IntegerField(blank=True, null=True ,validators =[validate_employees_Number])
    createdJobsNumber = models.IntegerField(blank=True, null=True)
    fullAddress = models.CharField(max_length=50,blank=True, null=True)

    GEEKS_CHOICES = (

        ("أدرار" , "أدرار"),
        ("الشلف" , "الشلف"),
        ("الأغواط" , "الأغواط"),
        ("أم البواقي" , "أم البواقي"),
        ("باتنة" , "باتنة"),
        ("بجاية" , "بجاية"),
        ("بسكرة" , "بسكرة"),
        ("بشار" , "بشار"),
        ("البليدة" , "البليدة"),
        ("البويرة" , "البويرة"),
        ("تمنراست" , "تمنراست"),
        ("تبسة" , "تبسة"),
        ("تلمسان" , "تلمسان"),
        ("تيارت" , "تيارت"),
        ("تيزي وزو" , "تيزي وزو"),
        ("الجزائر" , "الجزائر"),
        ("الجلفة" , "الجلفة"),
        ("جيجل" , "جيجل"),
        ("سطيف" , "سطيف"),
        ("سعيدة" , "سعيدة"),
        ("سكيكدة" , "سكيكدة"),
        ("سيدي بلعباس" , "سيدي بلعباس"),
        ("عنابة" , "عنابة"),
        ("قالمة" , "قالمة"),
        ("قسنطينة" , "قسنطينة"),
        ("المدية" , "المدية"),
        ("مستغانم" , "مستغانم"),
        ("المسيلة" , "المسيلة"),
        ("معسكر" , "معسكر"),
        ("ورقلة" , "ورقلة"),
        ("وهران" , "وهران"),
        ("البيض" , "البيض"),
        ("إليزي" , "إليزي"),
        ("برج بوعريريج" , "برج بوعريريج"),
        ("بومرداس" , "بومرداس"),
        ("الطارف" , "الطارف"),
        ("تيندوف" , "تيندوف"),
        ("تيسمسيلت" , "تيسمسيلت"),
        ("وادي سوف" , "وادي سوف"),
        ("سوق أهراس" , "سوق أهراس"),
        ("تيبازة" , "تيبازة"),
        ("عين الدفلى" , "عين الدفلى"),
        ("النعامة" , "النعامة"),
        ("عين تيموشنت" , "عين تيموشنت"),
        ("غرداية" , "غرداية"),
        ("غليزان" , "غليزان"),
    )                                                       
    
    wilaya = models.CharField(max_length=100,choices = GEEKS_CHOICES,blank=True, null=True)
    ownersEmail = models.EmailField(blank=True, null=True)
    ownersLinkedin = models.URLField(blank=True, null=True)
    contactEmail = models.EmailField(blank=True, null=True)
    mobilePhoneNumber = models.CharField(max_length=50,blank=True, null=True)
    mainPhoneNumber = models.CharField(max_length=50,blank=True, null=True)
    
    
    def __str__(self):
        
        return self.companyName  

    def get_addmin_url(self):
        
        return reverse ('adminapp' , args=[self.pk])   



def user_directory_path(instance, filename): 

    
  
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename> 
    return 'user_{0}/{1}'.format(instance.user.id, filename) 

class MultiStepFormModel(models.Model):

   
    Founder_CHOICES = (

        ("Founder" , "Founder"),
        ("Co-founder" , "Co-founder"),
       
    )                                                                                           
    
    Secture_CHOICES = (

        ("Fintech" , "Fintech"),
        ("Cloud/Sass" , "Cloud/Sass"),
        ("Agritech (agriculture de précision)" , "Agritech (agriculture de précision)"),
        ("Economie circulaire (greentech)" , "Economie circulaire (greentech)"),
        ("E-learning/ Edtech" , "E-learning/ Edtech"),
        ("Govtech (e-administration)" , "Govtech (e-administration)"),
        ("IOT (internet des objets)" , "IOT (internet des objets)"),
        ("Legaltech" , "Legaltech"),
        ("Food tech" , "Food tech"),
        ("E-health (santé)" , "E-health (santé)"),
        ("Smart City" , "Smart City"),
        ("IOT (internet des objets)" , "IOT (internet des objets)"),
        ("Tourisme/voyage" , "Tourisme/voyage"),
        ("Energies renouvelables" , "Energies renouvelables"),
        ("Pharma" , "Pharma"),
        ("Education" , "Education"),
        ("Intelligence Artificielle" , "Intelligence Artificielle"),
        ("Réalité augmentée/virtuelle" , "Réalité augmentée/virtuelle"),
        ("E-services" , "E-services"),
        ("Economie sociale et solidaire." , "Economie sociale et solidaire."),
        ("Cybersecurity" , "Cybersecurity"),
        ("Electronique &amp; Composants" , "Electronique &amp; Composants"),
        ("Jeux/loisir" , "Jeux/loisir"),
        ("Autre" , "Autre"),
        
       
    )     


    Progress_CHOICES = (

        ("Concept/Idea" , "Concept/Idea"),
        ("prototype in development" , "prototype in development"),
        ("prototype ready" , "prototype ready"),
        ("ready product" , "ready product"),
       
    )          
    id=models.AutoField(primary_key=True)
    Tname=models.CharField(max_length=225)
    fname=models.CharField(max_length=225)
    You_are =models.CharField(max_length=225)
    age=models.CharField(max_length=225)
    
    GEEKS_CHOICES = (

    ("أدرار" , "أدرار"),
    ("الشلف" , "الشلف"),
    ("الأغواط" , "الأغواط"),
    ("أم البواقي" , "أم البواقي"),
    ("باتنة" , "باتنة"),
    ("بجاية" , "بجاية"),
    ("بسكرة" , "بسكرة"),
    ("بشار" , "بشار"),
    ("البليدة" , "البليدة"),
    ("البويرة" , "البويرة"),
    ("تمنراست" , "تمنراست"),
    ("تبسة" , "تبسة"),
    ("تلمسان" , "تلمسان"),
    ("تيارت" , "تيارت"),
    ("تيزي وزو" , "تيزي وزو"),
    ("الجزائر" , "الجزائر"),
    ("الجلفة" , "الجلفة"),
    ("جيجل" , "جيجل"),
    ("سطيف" , "سطيف"),
    ("سعيدة" , "سعيدة"),
    ("سكيكدة" , "سكيكدة"),
    ("سيدي بلعباس" , "سيدي بلعباس"),
    ("عنابة" , "عنابة"),
    ("قالمة" , "قالمة"),
    ("قسنطينة" , "قسنطينة"),
    ("المدية" , "المدية"),
    ("مستغانم" , "مستغانم"),
    ("المسيلة" , "المسيلة"),
    ("معسكر" , "معسكر"),
    ("ورقلة" , "ورقلة"),
    ("وهران" , "وهران"),
    ("البيض" , "البيض"),
    ("إليزي" , "إليزي"),
    ("برج بوعريريج" , "برج بوعريريج"),
    ("بومرداس" , "بومرداس"),
    ("الطارف" , "الطارف"),
    ("تيندوف" , "تيندوف"),
    ("تيسمسيلت" , "تيسمسيلت"),
    ("وادي سوف" , "وادي سوف"),
    ("سوق أهراس" , "سوق أهراس"),
    ("تيبازة" , "تيبازة"),
    ("عين الدفلى" , "عين الدفلى"),
    ("النعامة" , "النعامة"),
    ("عين تيموشنت" , "عين تيموشنت"),
    ("غرداية" , "غرداية"),
    ("غليزان" , "غليزان"),
)   

    wilaya=models.CharField(max_length=225)
    fullAddress=models.CharField(max_length=225)
    Email=models.CharField(max_length=225)
    mainPhoneNumber=models.CharField(max_length=225)
    webLink=models.CharField(max_length=225)
    fbLink=models.CharField(max_length=225)
    ytubeLink=models.CharField(max_length=225 ,null=True , blank=True)
    prjname=models.CharField(max_length=225)
    prjfield=models.CharField(max_length=225 )
    file=models.FileField(upload_to = 'uploads/' ,null=True , blank=True )
    file_CV=models.FileField(upload_to = 'uploads/',null=True , blank=True)
    file_Br=models.FileField(upload_to = 'uploads/',null=True , blank=True)
    prjdetail=models.CharField(max_length=225)
    prjprgress=models.CharField(max_length=225)
    awards=models.CharField(max_length=225)
    objects=models.Manager()




class MultiStepFormModelBr(models.Model):
    
   
    Founder_CHOICES = (

        ("Founder" , "Founder"),
        ("Co-founder" , "Co-founder"),
       
    )                                                                                           
    
    Secture_CHOICES = (

        ("Fintech" , "Fintech"),
        ("Cloud/Sass" , "Cloud/Sass"),
        ("Agritech (agriculture de précision)" , "Agritech (agriculture de précision)"),
        ("Economie circulaire (greentech)" , "Economie circulaire (greentech)"),
        ("E-learning/ Edtech" , "E-learning/ Edtech"),
        ("Govtech (e-administration)" , "Govtech (e-administration)"),
        ("IOT (internet des objets)" , "IOT (internet des objets)"),

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
<h3 class="border-bottom">من أنا</h3>
{% endblock content %}

blog/templates/blog/app_list.html
{% extends 'blog/base.html' %}

{% block content %}
<h1 class="page-header">Books</h1>
<button class="btn btn-primary show-form" data-url="#">
    <span class="glyphicon glyphicon-plus"></span>
    New Book
</button>
<table class="table" id="book-table">
    <thead>
        <tr>
            <th>#</th>
            <th>companyName</th>
            <th>creationDate</th>
            <th>status</th>
            <th>associatesNumber</th>
            <th>employeesNumber</th>
            <th>createdJobsNumber</th>
            <th>fullAddress</th>
            <th>wlaya</th>
            <th>ownersEmail</th>
            <th>ownersLinkedin</th>
            <th>contactEmail</th>
            <th>mobilePhoneNumber</th>
            <th>mainPhoneNumber</th>

        </tr>
    </thead>
    <tbody>
        {% include "blog/app_list_2.html" %}
    </tbody>
</table>

<div class="modal fade" id="modal-book">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/app_list_2.html
{% for book in form %}
<tr>
    <td>{{ book.id }}</td>
    <td>{{ appregs.companyName}}</td>
    <td>{{ book.creationDate}}</td>
    <td>{{ book.status }}</td>
    <td>{{ book.associatesNumber}}</td>
    <td>{{ book.employeesNumber }}</td>
    <td>{{ book.createdJobsNumber }}</td>
    <td>{{ book.fullAddress }}</td>
    <td>{{ book.wlaya }}</td>
    <td>{{ book.ownersEmail }}</td>
    <td>{{ book.ownersLinkedin }}</td>
    <td>{{ book.contactEmail }}</td>
    <td>{{ book.mobilePhoneNumber }}</td>
    <td>{{ book.mainPhoneNumber }}</td>
    <td>
        <button class="btn btn-warning show-form-update" data-url="#">
            <span class="glyphicon glyphicon-pencil"></span>
            Edit
        </button>
    </td>
    <td>
        <button class="btn btn-danger show-form-delete" data-url="#">
            <span class="glyphicon glyphicon-trash"></span>
            Delete
        </button>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="7" class="text-center bg-warning">No book</td>
</tr>
{% endfor %}

blog/templates/blog/formmV.html
{% extends 'blog/base.html' %}
{% block content %}
{% load crispy_forms_tags %}







{% if messages%} {% for message in messages%} <div class="alert alert-warning"> {{message}}</div>
{%endfor%}
{% endif %}








<form method="POST" id="formmV" class="cmxform" novalidate="">

    {% csrf_token %}

    <div class="">
        <h4 class="text-center">معلومات عن الشركات الناشئة / الصغيرة</h4>
        <h5 class="text-center">
            يهدف هذا القسم إلى توفير معلومات حول نشاطك التجاري. يرجى أن تكون محددة وموجزة.
        </h5>
        <br>
        <div class="row">
            <div class="col-xs-offset-1 col-xs-10 col-sm-offset-1 col-sm-10">
                <div class="form-group">

                    <label class="control-label" for="{{ form.subject.id_for_label }}">اسم الشركة الناشئة</label>
                    <input class="form-control form-control-sm" type="text" name="companyName" value=""
                        placeholder="اسم الشركه" id="id_companyName" required>
                    {{data.companyName}}
                    {{data.companyName.errors}}


                </div>
                <div class="form-group">
                    <label class="control-label" for="creationDate">تاريخ الإنشاء</label>
                    <input class="form-control form-control-sm" type="date" name="creationDate"
                        value="{{data.creationDate}}" id="creationDate" placeholder="تاريخ الإنشاء" required>
                </div>

                <div class="form-group">
                    <label class="control-label" for="associatesNumber">عدد الشركاء</label>
                    <input class="form-control form-control-sm " id="associatesNumber" name="associatesNumber"
                        placeholder=" Nombre d'associées" type="number" value="{{data.associatesNumber}}">
                </div>
                <div class="form-group">
                    <label class="control-label" for="employeesNumber">عدد العاملين</label>
                    <p>
                        يرجى عدم إدراج مؤسسي / مالكي الشركة في عدد الموظفين.
                    </p>
                    <input class="form-control form-control-sm " id="employeesNumber" name="employeesNumber"
                        placeholder="Nombre d'employés" required type="number" value="{{data.employeesNumber}}">
                </div>
                <div class="form-group">
                    <label class="control-label" for="createdJobsNumber">
                        عدد الوظائف التي أنشأتها شركتك
                    </label>
                    <input class="form-control form-control-sm" id="createdJobsNumber" name="createdJobsNumber"
                        placeholder="عدد الوظائف التي أنشأتها شركتك" type="number" value="{{data.createdJobsNumber}}"
                        ng-reflect-model="0">
                </div>
                <div class="form-group">
                    <label class="control-label" for="status">الوضع القانوني</label>
                    <input class="form-control form-control-sm" id="status" name="status"
                        placeholder="SARL/EURL/SPA...etc." required type="text" value="{{data.status}}">

                </div>
                <div class="form-group">
                    <label class="control-label" for="fullAddress">العنوان الكامل</label>
                    <p>
                        يرجى كتابة العنوان بالضبط كما يظهر في الوثائق الرسمية للشركة.
                    </p>
                    <input class="form-control form-control-sm" id="fullAddress" name="fullAddress"
                        placeholder="العنوان الكامل" required type="text" ng-reflect-required=""
                        ng-reflect-name="fullAddress" value="{{data.associatesNumber}}">
                </div>
                <div class="form-group">
                    <label class="control-label" for="wilaya">الولاية</label>
                    <select class="form-control input-md ng-untouched ng-pristine ng-invalid" id="wilaya" name="wilaya"
                        required="True" ng-reflect-required="" ng-reflect-name="wilaya" ng-reflect-model="" value=''>

                        {{data.wilaya}}


                        bindings={
                        "ng-reflect-ng-for-of": "[object Object],[object Object"
                        }
                        <option value="0: أدرار" ng-reflect-ng-value="أدرار">1 - أدرار</option>
                        <option value="1: الشلف" ng-reflect-ng-value="الشلف">2 - الشلف</option>
                        <option value="2: الأغواط" ng-reflect-ng-value="الأغواط">3 - الأغواط
                        </option>
                        <option value="3: أم البواقي" ng-reflect-ng-value="أم البواقي">4 - أم
                            البواقي</option>
                        <option value="4: باتنة" ng-reflect-ng-value="باتنة">5 - باتنة</option>
                        <option value="5: بجاية" ng-reflect-ng-value="بجاية">6 - بجاية</option>
                        <option value="6: بسكرة" ng-reflect-ng-value="بسكرة">7 - بسكرة</option>
                        <option value="7: بشار" ng-reflect-ng-value="بشار">8 - بشار</option>
                        <option value="8: البليدة" ng-reflect-ng-value="البليدة">9 - البليدة
                        </option>
                        <option value="9: البويرة" ng-reflect-ng-value="البويرة">10 - البويرة
                        </option>
                        <option value="10: تمنراست" ng-reflect-ng-value="تمنراست">11 - تمنراست
                        </option>
                        <option value="11: تبسة" ng-reflect-ng-value="تبسة">12 - تبسة</option>
                        <option value="12: تلمسان" ng-reflect-ng-value="تلمسان">13 - تلمسان</option>
                        <option value="13: تيارت" ng-reflect-ng-value="تيارت">14 - تيارت</option>
                        <option value="14: تيزي وزو" ng-reflect-ng-value="تيزي وزو">15 - تيزي وزو
                        </option>
                        <option value="15: الجزائر" ng-reflect-ng-value="الجزائر">16 - الجزائر
                        </option>
                        <option value="16: الجلفة" ng-reflect-ng-value="الجلفة">17 - الجلفة</option>
                        <option value="17: جيجل" ng-reflect-ng-value="جيجل">18 - جيجل</option>
                        <option value="18: سطيف" ng-reflect-ng-value="سطيف">19 - سطيف</option>
                        <option value="19: سعيدة" ng-reflect-ng-value="سعيدة">20 - سعيدة</option>
                        <option value="20: سكيكدة" ng-reflect-ng-value="سكيكدة">21 - سكيكدة</option>
                        <option value="21: سيدي بلعباس" ng-reflect-ng-value="سيدي بلعباس">22 - سيدي
                            بلعباس</option>
                        <option value="22: عنابة" ng-reflect-ng-value="عنابة">23 - عنابة</option>
                        <option value="23: قالمة" ng-reflect-ng-value="قالمة">24 - قالمة</option>
                        <option value="24: قسنطينة" ng-reflect-ng-value="قسنطينة">25 - قسنطينة
                        </option>
                        <option value="25: المدية" ng-reflect-ng-value="المدية">26 - المدية</option>
                        <option value="26: مستغانم" ng-reflect-ng-value="مستغانم">27 - مستغانم
                        </option>
                        <option value="27: المسيلة" ng-reflect-ng-value="المسيلة">28 - المسيلة
                        </option>
                        <option value="28: معسكر" ng-reflect-ng-value="معسكر">29 - معسكر</option>
                        <option value="29: ورقلة" ng-reflect-ng-value="ورقلة">30 - ورقلة</option>
                        <option value="30: وهران" ng-reflect-ng-value="وهران">31 - وهران</option>
                        <option value="31: البيض" ng-reflect-ng-value="البيض">32 - البيض</option>
                        <option value="32: إليزي" ng-reflect-ng-value="إليزي">33 - إليزي</option>
                        <option value="33: برج بوعريريج" ng-reflect-ng-value="برج بوعريريج">34 - برج
                            بوعريريج</option>
                        <option value="34: بومرداس" ng-reflect-ng-value="بومرداس">35 - بومرداس
                        </option>
                        <option value="35: الطارف" ng-reflect-ng-value="الطارف">36 - الطارف</option>
                        <option value="36: تيندوف" ng-reflect-ng-value="تيندوف">37 - تيندوف</option>
                        <option value="37: تيسمسيلت" ng-reflect-ng-value="تيسمسيلت">38 - تيسمسيلت
                        </option>
                        <option value="38: وادي سوف" ng-reflect-ng-value="وادي سوف">39 - وادي سوف
                        </option>
                        <option value="39: خنشلة" ng-reflect-ng-value="خنشلة">40 - خنشلة</option>
                        <option value="40: سوق أهراس" ng-reflect-ng-value="سوق أهراس">41 - سوق أهراس
                        </option>
                        <option value="41: تيبازة" ng-reflect-ng-value="تيبازة">42 - تيبازة</option>
                        <option value="42: ميلة" ng-reflect-ng-value="ميلة">43 - ميلة</option>
                        <option value="43: عين الدفلى" ng-reflect-ng-value="عين الدفلى">44 - عين
                            الدفلى</option>
                        <option value="44: النعامة" ng-reflect-ng-value="النعامة">45 - النعامة
                        </option>
                        <option value="45: عين تيموشنت" ng-reflect-ng-value="عين تيموشنت">46 - عين
                            تيموشنت</option>
                        <option value="46: غرداية" ng-reflect-ng-value="غرداية">47 - غرداية</option>
                        <option value="47: غليزان" ng-reflect-ng-value="غليزان">48 - غليزان</option>
                    </select>
                    <div class="alert alert-danger" hidden="">wilaya is required</div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="id_ownersEmail">عنوان البريد الإلكتروني
                        للمدير</label>
                    <input class="form-control form-control-sm " id="id_ownersEmail" name="ownersEmail"
                        placeholder="عنوان البريد الإلكتروني للمدير" required="" type="text"
                        value="{{data.ownersEmail}}" required>

                </div>

                <div class="form-group">
                    <label class="control-label" for="id_ownersLinkedin">لينكدين المدير</label>
                    <input class="form-control form-control-sm
                                    id =" id_ownersLinkedin" name="ownersLinkedin" placeholder="لينكدين المدير"
                        type="url" value="{{data.ownersLinkedin}}" required>
                </div>

                <div class="form-group">
                    <label class="control-label" for="id_contactEmail">عنوان البريد الإلكتروني
                        للاتصال</label>
                    <p>
                        عنوان البريد الإلكتروني الذي تريد الاتصال به للمشاريع أو التعاونات
                        المستقبلية. يمكن أن يكون هذا هو نفس البريد الإلكتروني كما هو موضح أعلاه.
                    </p>
                    <input class="form-control form-control-sm " id="id_contactEmail" name="contactEmail"
                        placeholder="عنوان البريد الإلكتروني للاتصال" required type="email"
                        value="{{data.contactEmail}}">

                </div>
                <div class="form-group">
                    <label class="control-label" for="mobilePhoneNumber">الهاتف المحمول</label>
                    <p>
                        سيتم إرسال رقم الهاتف هذا إلى الشركاء المحتملين للمشروع في حالة الاهتمام
                        بنشاط الشركة. يرجى تقديم رقم هاتف يمكن الاتصال بشركتك في أي وقت.
                    </p>
                    <input class="form-control form-control-sm" id="mobilePhoneNumber" name="mobilePhoneNumber"
                        pattern="(\+|00){0,2}[0-9]{2,14}" placeholder="الهاتف المحمول" required type="tel"
                        value="{{data.mobilePhoneNumber}}">
                </div>

                <div class="form-group">
                    <label class="control-label" for="mainPhoneNumber">الهاتف الرئيسي</label>
                    <input class="form-control form-control-sm " id="mainPhoneNumber" name="mainPhoneNumber"
                        placeholder="الهاتف الرئيسي" required value="{{data.mainPhoneNumber}}">
                </div>
            </div>

        </div>
        <input class="btn-1 btn btn-primary py-2 mb-3" type="submit" value="تسجيل">
    </div>
</form>

{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base_index.html' %}
{% load static %}
{%block headerphoto%}
<img class="img-fluid" id="img" src="{% static 'blog/images/Banner.jpg' %}" alt="logo">
{% endblock headerphoto%}

{% block content %}



{% endblock content %}